Beacon v2 default schemas v2.0 intitial YAML files
ga4gh-beacon/specification-v2-default-schemas pull request #14
Opened 2021-01-11 15:46 UTC by mamanambiya

Hi all,

Initial translation of beacon v2 default schema from [the documentation](https://github.com/ga4gh-beacon/specification-v2-default-schemas/blob/develop/beacon_v2_default_schemas_v2.0.pdf) into YAML files.

2021-01-11 16:41 UTC, mbaudis commented on default_biosample_schema.yaml
> +            Reference to subject ID (Subject.subjectId).
IMO it should be `subjectId` which references `subject.id`; and similar throughout.

2021-01-11 16:45 UTC, mbaudis commented on default_subject_schema.yaml
> +        subjectId:
IMO (and consistent with other uses so far) should be `id`, the "resource-local id of the subject / individual", referenced as `subject.id`.

2021-01-11 17:07 UTC, mbaudis commented on default_subject_schema.yaml
> +            Ethnic background of subject. Value from NCIT Race ontology
* do not specify "NCIT race ontology" as sole reference (this is the same everywhere - ontologies may be given as example or even recommendation, but not prescribed as "use this")
* a system using the word "race" in its name kind of disqualifies itself as something not related to underlying biology or "ethnicity"
* HANCESTRO is a better example since probabilistic (IMO): `id: "HANCESTRO:0014", label: "Hispanic or Latin American"`
* all of these identifiers should be represented as `OntologyTerm` objects (see the `id`, `label` HANCESTRO example

2021-01-12 07:34 UTC, sdelatorrep commented
Hi @mbaudis 
@jrambla and @clauw87 will check your suggestions regarding ontologies and IDs.
But this conversion that Mamana has done is based on the **current PDF**. Once this is merged, we will start changing many things.
So, I suggest to look for typos, errors, etc., and, after merging, then discuss (e.g. using issues) how to improve it (e.g. use `label` & `id` for all the ontologies instead of string).

2021-01-12 07:40 UTC, mbaudis commented
> But this conversion that Mamana has done is based on the **current PDF**. Once this is merged, we will start changing many things.

O.k. But this also shows that using a PDF as implementation guide is very, very ... strange. There is no track record of how this was generated and no way for fixing. It is super easy to derive documentation from a commented schema - it is impossible to derive a schema from a PDF doc...

2021-01-12 07:49 UTC, sdelatorrep commented
I agree! Once we have a version which reflects the PDF, we can get rid of it and only work with OpenAPI definitions. WDYT @jrambla, @clauw87 ?

2021-01-12 11:44 UTC, sdelatorrep requested changes

2021-01-12 11:44 UTC, sdelatorrep commented on default_variant_annotations_schema.yaml
> +            $ref: '#/components/schemas/ClinicalRelevance'
The referenced schema `ClinicalRelevance` does not exist in this YAML. I think it's a typo and should point to `#/components/schemas/GenomicFeature`.

2021-01-12 11:44 UTC, sdelatorrep commented on default_variant_annotations_schema.yaml
>        properties:
There is a missing property: `genomicRegion`.

2021-01-12 11:44 UTC, sdelatorrep commented on default_variant_annotations_schema.yaml
>          geneIds:
This property is not in the PDF.

2021-01-12 11:44 UTC, sdelatorrep commented on default_variant_annotations_schema.yaml
>            type: array
This property does not exist in the document: `clinicalRelevance`.

2021-01-12 11:44 UTC, sdelatorrep commented on default_variant_annotations_schema.yaml
> +    genomicFeatures:
Should be `GenomicFeature` (singular and capital letter).

2021-01-12 11:44 UTC, sdelatorrep commented on default_variant_annotations_schema.yaml
>          variantGeneRelationship:
This property does not exist in the PDF.

2021-01-12 11:44 UTC, sdelatorrep commented on default_variant_in_sample_schema.yaml
> +    phenotypicEffect:
Should start with a capital letter.

2021-01-12 11:44 UTC, sdelatorrep commented on default_variant_schema.yaml
> +  title: GA4GH Beacon Variant Default Schema
This file defined the old Variant Identification definition. As we now have a new file called `default_variant_identification_schema.yaml`, this one should be deleted.

2021-01-12 15:41 UTC, mamanambiya commented on default_biosample_schema.yaml
> +            Reference to subject ID (Subject.subjectId).
It was decided at the call today to use the term individual instead of subject. So I going to change everything back to individual and ensure there is consistency everywhere.

2021-01-13 11:52 UTC, mbaudis commented on default_biosample_schema.yaml
> +            Reference to subject ID (Subject.subjectId).
Still - the schemas should have an `id` and be referenced by `schemascope.id`, as above...

2021-01-13 12:00 UTC, mbaudis commented on default_biosample_schema.yaml
>    schemas:
@sdelatorrep Correct; but the reason for this object was an original use in GA4GH metadata -> Phenopckets ... where also age classes etc. were used. It seems fine to just go with ISO8601 string here, w/o any additional wrapper etc. And we stick w/ **ISO duration**, but w/o the "anchored" option I had documented before which seems confusing. See discussion for [PXF v2](https://github.com/phenopackets/phenopacket-schema/issues/254#issuecomment-747540538).

2021-01-13 12:12 UTC, mbaudis commented on default_subject_schema.yaml
> +        level_severity: #todo '/'' or 'or'
Again, please create all references to ontologies ... as [`OntologyClass` objects](https://schemablocks.org/schemas/sb-phenopackets/OntologyClass.html). As side effect this allows for better documentation:
```
stage:
  $ref: '#/components/schemas/OntologyClass
example:
  id : "NCIT:C90529",
  label : "AJCC v6 Stage"
```
The $ref obv. has to be adjusted to the correct representation. 

N.B.: Do not use SNOMED examples - not a free ontology.

2021-02-09 15:05 UTC, mbaudis commented on default_subject_schema.yaml
> +        subjectId:
... but actually should be individual / individualId.

2021-02-23 21:37 UTC, mamanambiya commented on default_biosample_schema.yaml
> +            Reference to subject ID (Subject.subjectId).
> Still - the schemas should have an `id` and be referenced by `schemascope.id`, as above...

This should be considered in future submissions as this PR is purely a translation of the **current PDF** document.

2021-02-24 10:58 UTC, mamanambiya commented on default_biosample_schema.yaml
> +            Reference to subject ID (Subject.subjectId).
`subject` term changed to `individual` Commit [283872b](https://github.com/ga4gh-beacon/specification-v2-default-schemas/pull/14/commits/283872b44564a1379287097d625801f5fbc62ba9)

2021-02-24 11:06 UTC, mamanambiya commented on default_biosample_schema.yaml
> +        subjectAgeAtCollection:
Fixed in commit [28d2c0e](https://github.com/ga4gh-beacon/specification-v2-default-schemas/pull/14/commits/28d2c0ef1e532ed925068e9a6c1c0c0a53f4ca68)

2021-02-24 11:06 UTC, mamanambiya commented on default_biosample_schema.yaml
>    schemas:
Fixed in commit 28d2c0e

2021-02-24 11:08 UTC, mamanambiya commented on default_subject_schema.yaml
>        properties:
Fixed in commint [41f4ccc](https://github.com/ga4gh-beacon/specification-v2-default-schemas/pull/14/commits/41f4ccc724a348547e440cceda41ddf01c0c1fe9)

2021-02-24 11:08 UTC, mamanambiya commented on default_subject_schema.yaml
> +      properties:
Fixed in commint 41f4ccc

2021-02-24 11:10 UTC, mamanambiya commented on default_variant_annotations_schema.yaml
> +            $ref: '#/components/schemas/ClinicalRelevance'
Fixed in commit [067dd95](https://github.com/ga4gh-beacon/specification-v2-default-schemas/pull/14/commits/067dd9551f82f82b1b684c5ab645ecbef922e31d)

2021-02-24 11:10 UTC, mamanambiya commented on default_variant_annotations_schema.yaml
>        properties:
Fixed in commit [067dd95](https://github.com/ga4gh-beacon/specification-v2-default-schemas/pull/14/commits/067dd9551f82f82b1b684c5ab645ecbef922e31d)

2021-02-24 11:10 UTC, mamanambiya commented on default_variant_annotations_schema.yaml
>          geneIds:
Fixed in commit [067dd95](https://github.com/ga4gh-beacon/specification-v2-default-schemas/pull/14/commits/067dd9551f82f82b1b684c5ab645ecbef922e31d)

2021-02-24 11:10 UTC, mamanambiya commented on default_variant_annotations_schema.yaml
> +    genomicFeatures:
Fixed in commit [067dd95](https://github.com/ga4gh-beacon/specification-v2-default-schemas/pull/14/commits/067dd9551f82f82b1b684c5ab645ecbef922e31d)

2021-02-24 11:10 UTC, mamanambiya commented on default_variant_annotations_schema.yaml
>          variantGeneRelationship:
Fixed in commit [067dd95](https://github.com/ga4gh-beacon/specification-v2-default-schemas/pull/14/commits/067dd9551f82f82b1b684c5ab645ecbef922e31d)

2021-02-24 11:11 UTC, mamanambiya commented on default_variant_in_sample_schema.yaml
> +    phenotypicEffect:
Fixed in commit [9cb2a26](https://github.com/ga4gh-beacon/specification-v2-default-schemas/pull/14/commits/9cb2a265d70c28368142aafa3fab709709b3bd76)

2021-02-24 11:12 UTC, mamanambiya commented on default_variant_schema.yaml
> +  title: GA4GH Beacon Variant Default Schema
File deleted in commit [e084cf6](https://github.com/ga4gh-beacon/specification-v2-default-schemas/pull/14/commits/e084cf6e51d9c68076a17496888dd41a1ba4e20a)

2021-02-24 12:22 UTC, sdelatorrep approved these changes

2021-02-24 13:48 UTC, merged