Fix distribution property
ga4gh-beacon/specification-v2-default-schemas pull request #23
Opened 2021-03-02 13:36 UTC by MrRobb

## Changes

Update distribution property according to the documentation of the cohorts.

2021-03-02 15:43 UTC, sdelatorrep requested changes

2021-03-02 15:43 UTC, sdelatorrep commented on default_cohort_schema.yaml
> +        type:
All ontology fields have this structure. There should be a type, e.g. `OntologyTerm`, defined in `common.yaml` and this should be used everywhere in the YAMLs.

2021-03-02 19:57 UTC, mbaudis commented on default_cohort_schema.yaml
> +        type:
Yes, instead of id, label explicitly defined.

2021-03-03 16:02 UTC, sdelatorrep approved these changes

2021-03-03 16:02 UTC, merged